name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Login
      uses: actions-hub/docker/login@master
          env:
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }} 
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }} 
    - name: Build
      uses: okteto/actions/build@v1
         with:
           token: ${{ secrets.OKTETO_TOKEN }}
           tag: ${{ secrets.DOCKER_USERNAME }}/hello-world:${{ github.sha }}
    - name: Get Kubeconfig
      uses: okteto/actions/namespace@v1
         id: namespace
         with:
           token: ${{ secrets.OKTETO_TOKEN }}
           namespace: actions-rberrelleza
    - name: Deploy and Wait
      uses: okteto/actions/deploy@v1
        env:
         KUBECONFIG: ${{ steps.namespace.outputs.kubeconfig }}  
        with:
         namespace: actions-rberrelleza
         manifest: k8s.yml
         tag: ${{ secrets.DOCKER_USERNAME }}/hello-world:${{ github.sha }}
         waitOn: deployment/hello-world
    - name: Verify
      uses: srt32/uptime@master
      with:
        url-to-hit: "https://hello-world-henrik-geissler.cloud.okteto.net"
        expected-statuses: "200"
