on: [push]

name: CI

jobs:
  devflow:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
      
    - uses: okteto/login@master
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
    
    - name: "Activate personal namespace"
      uses: okteto/namespace@master
      with:
        name: henrik-geissler

    
    - name: "Create deployment"
      uses: okteto/apply@master
      with:
        manifest: okteto-pipeline.yml
        args: "validate=false"
    - name: Verify
      uses: srt32/uptime@master
      with:
        url-to-hit: "https://polling-henrik-geissler.cloud.okteto.net/api"
        expected-statuses: "200" 
