
on:
  push:
    branches:
      - main

name: PR

jobs:
  devflow:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master    

    - name: Login
      uses: okteto/login@master
      with:
        token: ${{ secrets.OKTETO_TOKEN }}

    - name: "Activate Namespace"
      uses: okteto/namespace@master
      with:
        name: henrik-geissler
    
    - name: "Trigger the pipeline"
      uses: okteto/pipeline@master
      with:
        name: mehrweg-api
        timeout: 8m
