
on:
  push:
    branches:
      - main

name: PR
  
jobs:
  swagger:
    runs-on: ubuntu-latest
    steps:
    - name: Generate Swagger UI
      uses: Legion2/swagger-ui-action@v1
      with:
        output: swagger-ui
        spec-file: openapi.yaml
        #swagger-config-file:
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: swagger-ui
  devflow:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master    

    - name: Login
      uses: okteto/login@master
      with:
        token: ${{ secrets.OKTETO_TOKEN }}

    - name: "Activate Namespace"
      uses: okteto/namespace@master
      with:
        name: henrik-geissler
    
    - name: "Trigger the pipeline"
      uses: okteto/pipeline@master
      with:
        name: mehrweg-api
        timeout: 8m
