on: [push]

name: CI

jobs:

  devflow:
    runs-on: ubuntu-latest
    steps:
    
    - uses: okteto/login@master
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
    
    - name: "Activate Namespace"
      uses: okteto/namespace@master
      with:
        namespace: henrik-geissler
    
    - name: "Deploy application"
      uses: okteto/apply@master
      with:
        namespace: henrik-geissler

    - name: "Push changes"
      uses: okteto/push@master
      with:
        namespace: henrik-geissler
        name: hello-world
