
on:
  pull_request:
    branches:
      - main

name: PR

jobs:
  devflow:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master    

    - name: Login
      uses: okteto/login@master
      with:
        token: ${{ secrets.OKTETO_TOKEN }}

    - name: "Activate Namespace"
      uses: okteto/namespace@master
      with:
        name: henrik-geissler
    
    - name: "Trigger the pipeline"
      uses: okteto/pipeline@master
      with:
        name: pr-${{ github.event.number }}
        timeout: 8m
    - name: Verify
      uses: srt32/uptime@master
      with:
        url-to-hit: "https://polling-henrik-geissler.cloud.okteto.net/api"
        expected-statuses: "200" 
